[book]
title = "nfsen-ng"
authors = ["Michael Bolli"]
language = "en"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
fold.enable = true
git-repository-url = "https://github.com/mbolli/nfsen-ng"
additional-css = ["theme/lightbox.css"]
additional-js = ["theme/lightbox.js"]
